### ISSUE TITLE
TODO: Auth - Frameworks Support

### ISSUE THREAD

**Issue by stachu540** [GlitchLib/glitch#13]
* [ ] [Spring Framework](https://spring.io/) 
* [ ] [Play Framework](https://www.playframework.com/)
* [ ] [Eclipse Vert.x](https://vertx.io/)
* [ ] [Akka](https://akka.io/)
* [ ] [Ktor](https://ktor.io/)
