### ISSUE TITLE
TODO: Test Environment

### ISSUE THREAD

**Issue by stachu540** [GlitchLib/glitch#14]
* [ ] `glitch-core` - Auth endpoints
* [ ] `glitch-auth` - Mocking Auth endpoints
* [ ] `glitch-socket`
  * [ ] URI test
  * [ ] Mocking Dispatcher
* [ ] `glitch-chat`
  * [ ] Message Parse
  * [ ] Commands Parse
* [ ] `glitch-pubsub`
* [ ] `glitch-kraken` & `glitch-helix`
  * [ ] Mocking response
  * [ ] Asserting requests
