### ISSUE TITLE
TODO: Events

### ISSUE THREAD

**Issue by stachu540** [GlitchLib/glitch#15]
This issue provides only Events. It should be Immutable and documented. All events must be extends a `Event` from **Core Websocket**

## Core Websocket
* [x] `Event` - Contains Client Endpoint
  * [x] `OpenEvent` - connection into websocket has been established
  * [x] `CloseEvent` - closing websocket connection
  * [x] `PingEvent` - receiving ping from the server
  * [x] `PongEvent` - receiving pong from the server
  * [x] `RawByteMessageEvent` - receiving message into `ByteBuffer`
  * [x] `RawMessageEvent` - receiving message into `String`

## Message Interface - `glitch-chat`
* [x] `RawIRCEvent`
* [x] `GlobalUserStateEvent`
  * [x] `UserStateEvent`
* [x] `ChannelEvent`
  * [x] `NoticeEvent`
* [x] `UserEvent`
* [x] `ChannelUserEvent` - extends `ChannelEvent`, `UserEvent`
  * [x] `BanEvent`
  * [x] `ClearChatEvent`
  * [x] `HostEvent`
  * [x] `JoinEvent`
  * [x] `PartEvent`
  * [x] `RaidEvent`
  * [x] `RoomStateEvent`
  * [x] `RoomStateChangedEvent`
  * [x] `TimeoutEvent`
  * [x] `UnhostEvent`
  * [x] `UnbanEvent`
  * [x] `SubscriptionEvent`
  * [x] `SubscriptionGiftEvent`
  * [x] `NewChatterEvent`
  * [x] `RitualNoticeEvent`
  * [x] `MessageEvent`
  * [x] `BitsMessageEvent`
  * [x] `PrivateMessageEvent`

## PubSub - `glitch-pubsub`
* [x] `ListenEvent`
* [x] `UnistenEvent`
* [x] `MessageReceivedEvent`
---
* [x] `BitsEvent`
* [x] `CommerceEvent`
* [x] `ExtensionDataEvent`
* [x] `FollowEvent`
* [x] `GiftSubscriptionEvent`
* [x] `ModerationEvent`
  * [x] `BanEvent`
  * [x] `ModEvent`
  * [x] `UnmodEvent`
  * [x] `TimeoutEvent`
  * [x] `UnbanEvent`
* [x] `PrivateMessageEvent`
* [x] `StreamCounterEvent`
* [x] `StreamStartEvent`
* [x] `StreamStopEvent`
* [x] `SubscriptionEvent`
