### ISSUE TITLE
v1 Tracker

### ISSUE THREAD

**Issue by stachu540** [GlitchLib/glitch#42]
# General and Core

* [ ] Full Kotlin Support (jvm only this version) - Multiplatform in v2
  * [ ] `kotlinx.serialization`
  * [ ] `kotlinx.coroutines`
  * [ ] `io.ktor`
  * [ ] DSL support
* [ ] Enchancement website
  * [ ] UI improvements (colors, dark mode, search bar etc.)
  * [ ] Documentation merge into hugo using `dokka`
  * [ ] Bootstrap updates
* [ ] Starting test unit for queries
* [ ] General Availablility endpoints
* [ ] Improvement OAuth2 soultions for Spring Framework
* [ ] `WebSocketApi` solutions
  * [ ] `Event` API
* [ ] `RestApi` solutions
  * [ ] `RestAction` API (with timeouts)
    * [ ] Direct coroutine result
    * [ ] Enqueued result
  * [ ] Apply `kotlinx.serialization`

# Chat / PubSub

* [ ] Chat implementations
  * [ ] IRC API for Kotlin
  * [ ] Commands API
  * [ ] Test Unit using [fdgt](https://fdgt.dev/) solution
* [ ] Enchance more Events from `WebSocketApi`
* [ ] RawEvents handling and converts to specific requested event

# Kraken / Helix

* [ ] IRC API for Kotlin
* [ ] Commands API
* [ ] Enchance more Events from `WebSocketApi`
* [ ] [`kraken`] Video Uploads - see #25

# BOM

* [ ] use Gradle's `dependencies.constraints`, rather than `io.spring.dependency-management` plugin

# WebSub

* [ ] Create implementation for `helix` resolvers
* [ ] Create implementation using a custom `FlowAction` named webhook resolver
